export enum Positions {
  financeManagerPos = 'financeManagerPos',
  accountsManagerPos = 'accountsManagerPos',
  seniorAccountantPos = 'seniorAccountantPos',
  juniorAccountantPos = 'juniorAccountantPos',
  payrollAccountantPos = 'payrollAccountantPos',
  dataEntryPos = 'dataEntryPos',

  HRManagerPos = 'HRManagerPos',
  seniorAdministratorPos = 'seniorAdministratorPos',
  govermentalOfficerPos = 'govermentalOfficerPos',
  coordinatorPos = 'coordinatorPos',
  payrollOfficerPos = 'payrollOfficerPos',

  salesAssociatePos = 'salesAssociatePos',
  salesOperationCoordinatorPos = 'salesOperationCoordinatorPos',
  retailStoreManagerPos = 'retailStoreManagerPos',
  majorAccountManagerPos = 'majorAccountManagerPos',
  directorOfSalesPos = 'directorOfSalesPos',

  itManagerPos = 'itManagerPos',
  programmingEngineerPos = 'programmingEngineerPos',
  hardwareMaintemancePos = 'hardwareMaintemancePos',
  troubleShootingPos = 'troubleShootingPos',
  networkingPos = 'networkingPos',

  marketingCoordinatorPos = 'marketingCoordinatorPos',
  marketingAnalystPos = 'marketingAnalystPos',
  marketingSpecialistPos = 'marketingSpecialistPos',
  accountExecutivePos = 'accountExecutivePos',
  marketingAssociatePos = 'marketingAssociatePos',
  marketingAssistantPos = 'marketingAssistantPos',
  marketingManagerPos = 'marketingManagerPos',
  onlineMarketingSpecialistPos = 'marketingAnalystPos',
}
